version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DB
    ports:
      - "5432:5432"
